### ISSUE TITLE
ps-y-reach-end and ps-y-reach-start called one after another

### ISSUE THREAD

**Issue by ujtordai** [zefoy/ngx-perfect-scrollbar#102]
Hi All,

I have a problem, the two events _ps-y-reach-end_ and _ps-y-reach-start_ called one after another.
Which is that case when can occurring this?

Thank you in advance

**Comment by ujtordai** [comment]
Hi

I notified about this problem the owner of the perfect-scrollbar Hyunje Jun, and he suggested to me to ask you to update the dependencies of ngs-perfect-scrollbar to tha latest perfect-scrollbar v1.1.0
Here is the post: []https://github.com/utatti/perfect-scrollbar/issues/705
Thank you in advance

**Comment by sconix** [comment]
Yes there is new release coming that uses perfect-scrollbar 1.x but I am waiting for new release of it since in the current version there is still issue that prevent me releasing this library. The issue has been already fixed and I am just waiting that new perfect-scrollbar release with that fix is made. So as soon as its out there will be 4.9.3 release which uses 1.x perfect-scrollbar.

**Comment by ujtordai** [comment]
Ok, thank you

**Comment by sconix** [comment]
I am releasing 4.9.2 today which uses ps 1.x and therefore this issue should be fixed.

**Comment by ujtordai** [comment]
Great thank you of your notification.
