### ISSUE TITLE
Compliant with Angular Universal

### ISSUE THREAD

**Issue by Flood** [zefoy/ngx-perfect-scrollbar#104]
I've just tried implementing this lib in my Angular Universal application and it crashes in the server rendered version of my app. 

`TypeError: element.getAttribute is not a function`

and

`Cannot read property 'add' of undefined`

Will this lib be compliant with Universal soon?

**Comment by sconix** [comment]
This is just a wrapper, you should make an issue for the perfect-scrollbar repository about server rendering support.

**Comment by sconix** [comment]
I just got an idea. You should be able to set the perfect-scrollbar as disabled when server rendering then the perfect-scrollbar instance is never created.

**Comment by GrandSchtroumpf** [comment]
Any idea how to do that ?
My PerfectScrollbarModule is imported in shared.module.ts. As far as I know there is no way to check if we are on the server or the browser in ngModule since we need @Inject(PLATFORM_ID).

**Comment by sconix** [comment]
Well I have no experience in the server side rendering, but you can always check if document/window is available.

**Comment by GrandSchtroumpf** [comment]
Unfortunately I cannot achieve that, else it doesn't want to build the component with <perfect-scrollbar> inside ... I'm thinking about not using Angular-Universal as a solution ^^

**Comment by sconix** [comment]
What do you mean, that it does not build with perfect-scrollbar component? I can't see a reason why it would not. Have you tried just settings [disabled]="true" to the perfect-scrollbar component?

**Comment by GrandSchtroumpf** [comment]
Yes I tried. But the problem comes from the import of PerfectScrollbarModule. When I build :
- If you import the module with <perfect-scrollbar [disabled]="isServer">, it throw "Element is not defined"
- If you import the module after checking if "window" exists for example, and <perfect-scrollbar [disabled]="isServer">, it throw that <perfect-scrollbar> is not defined ...

**Comment by laurentgoudet** [comment]
- `Element is not defined` & similar errors are caused by `perfect-scrollbar` evaluating browser-specific constructs in its top level module scopes, a.k.a. not being SSR friendly. See https://github.com/utatti/perfect-scrollbar/issues/727 for the details and https://github.com/utatti/perfect-scrollbar/pull/728 for the fix.

- `<perfect-scrollbar [disabled]="isServer">` would then work but is not really convenient as one then has to use it on every single `<perfect-scrollbar>` instance. A better approach IMO is to build SSR support directly into `ngx-perfect-scrollbar` as per https://github.com/zefoy/ngx-perfect-scrollbar/pull/129, which uses the `PLATFORM_ID` technique described in https://angular.io/guide/universal#the-root-appmodule.

**Comment by sconix** [comment]
Sure I can add automatic checking for SSR when there is a release of perfect-scrollbar that wont cause problems.
