### ISSUE TITLE
Can't use pull down menu content scroll

### ISSUE THREAD

**Issue by armangevorgyan** [zefoy/ngx-perfect-scrollbar#108]
https://gyazo.com/c9bd96be89506a64d953612e0441c014

**Comment by sconix** [comment]
You need to stop the events propagation for the scroll events from the dropdown menu. Or if possible use this for the dropdown as well when you can use the propagation configuration.

**Comment by armangevorgyan** [comment]
Thanks, when i change ngx-perfect-scroll to 4.9.1 and its start work ) .
But now i have another problem, i cant change scrollbar position https://gyazo.com/0ff24bea589aae1b9e69fe8d0f69cc9b

**Comment by sconix** [comment]
The 4.9.x releases are not fully functional. They use PS 1.x and I am waiting for a new release of it that fixes the problems so that I can release a working 4.9.x release. So you should wait for 4.9.2 release. But its possible that it fixes your problem the PS 1.x has some tweaks in scroll handling etc. but its also possible that it works for you due to bugs. I am hoping that the new release of PS is out during this week so that I could get a new release out.

**Comment by armangevorgyan** [comment]
Thank you for your fast response

**Comment by sconix** [comment]
I just released 4.9.2 which uses PS 1.x (1.2.0 required) and is fully working. Please open a new issue if ou still have problems with the latest version.
