### ISSUE TITLE
Error when upgrading to version 5

### ISSUE THREAD

**Issue by meloks** [zefoy/ngx-perfect-scrollbar#116]
Not sure if this is the module issue, but when upgrading Angular and Ngx-perfect-scrollbar to version 5, I can see this error in the console:

Error: Module not already loaded loading "../../Observable" as http://localhost:8000/Observable.js.
  Evaluating http://localhost:8000/lib/ngx-perfect-scrollbar/bundles/ngx-perfect-scrollbar.umd.js

I am using System.Js

Please advise..

**Comment by sconix** [comment]
Angular 5 needs rxjs 5.5.2 which does not work with SystemJS. There is supposedly a fix coming in next release. Although the error is different, but at least I cant make systemjs app working without the patch coming most likely in next rxjs release. Anyway I have verified this lib to work with SystemJS with the patch, but cant link the issue since I am on mobile atm.

**Comment by meloks** [comment]
Thanks for the clarification...

**Comment by sconix** [comment]
Actually the error you were seeing was due to error in my UMD bundle packaging. I have fixed this for 5.0.1, but this wont of course remove the problem with SystemJS and rxjs 5.5.2. Anyway for that issue there are workarounds.
