### ISSUE TITLE
performance problems

### ISSUE THREAD

**Issue by munkk** [zefoy/ngx-perfect-scrollbar#123]
Hello, the project i'm working on has many components, and it seems, that scrollbar invokes change detection cycle too often, it impacts on performance. Is there any solution to fix it?
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13670003/33184168-57ee7c06-d08c-11e7-840c-3ccb316998ff.gif)

**Comment by sconix** [comment]
It should not trigger change detection at all unless you are using scroll indicators or auto propagation. Are you listening to scroll events etc.?

**Comment by munkk** [comment]
i'm listening only 'mouseenter' and 'mouseleave' events on the host component to toggle scrollbar opacity, like on the pic. if i disable them, nothing will change.
![image](https://user-images.githubusercontent.com/13670003/33209459-ebeeaa3a-d126-11e7-8244-f79bba4458d1.png)

**Comment by sconix** [comment]
And you have verified that without perfect-scrollbar (i.e. with normal scroll) there is no issues? I guess your code is not public anywhere?

I will have a quick look during the weekend if some performance bug has slipped back. At least we haven't noticed any performance problems in our project where we also have large / multiple / complex components inside the perfect-scrollbar. Although we are using onPush so it could hide the problem.

**Comment by munkk** [comment]
Without perfect-scrollbar there are too some performance issues, but not as heavy as with scrollbar directive.
You can compare two versions here- https://github.com/munkk/ng2/tree/perfectScroll,
attached directive located here https://github.com/munkk/ng2/blob/d4f8d692bdcf8cb0aeb86825396b31b83680852f/src/main/core/table/table-core.component.html , just detach and reattach this directive to see the difference) 
hope this will not take too much of your weekend time, thanks!

**Comment by sconix** [comment]
I had a quick look and I barely noticed any difference in the performance. Its noticeable true, but without perfect-scrollbar I would expect seeing totally smooth scroll, but instead I saw some constant model changes etc. The thing that got my attention was the scroll top changes logging, so I did quick grep and found out that you do add event listener to scroll event to update the elements positions. And thats the reason for the performance lost. First of all that causes browser do repainting which in turn re-renders the perfect-scrollbar and like with all repainting its slow, so thats the reason why perfect-scrollbar makes the scrolling even slower. The main reason though is that you are listening to scroll event and don't have any throttling in it. Browser sends the event many many times per second and you do heavy DOM operation on every event then you will get very unresponsive UI. Not sure if throttling can make such many position changes smooth, but at least it will help a lot.

So I can say for sure that the performance issue is not due to this library, and basically its not even because of perfect-scrollbar. You can't avoid some performance loss when using scroll libraries like perfect-scrollbar, but with proper application code the performance loss is unnoticeable. I.e. when you keep the DOM changes to minimum while scrolling there is very little difference in the performance.

**Comment by munkk** [comment]
now it's clear. thanks a lot)
