### ISSUE TITLE
Indicate if custom scrollbar is active

### ISSUE THREAD

**Issue by marvinhuebner** [zefoy/ngx-perfect-scrollbar#127]
The vanilla perfect-scrollbar renders a `ps--active-y` class if the vertical scrollbar is active and a `ps--active-x`class on the scrollbar container.

In the `ngx-perfect-scrollbar` case the container would be the `<perfect-scrollbar>` component.

Is it somehow possible to have such a class on the container, to indicate if the scrollbar is active?

I need this because i like to adjust some css style on the `.ps-content` element if the user can scroll.

**Comment by sconix** [comment]
This just wraps the perfect-scrollbar so the ps--active classes are in the perfect-scrollbar container just like with vanilla perfect-scrollbar. You should not need to have those classes in the <perfect-scrollbar> component since you are anyway styling ps-content which is inside the perfect-scrollbar container.

You can have a look at the component style sheet how it styles based on those perfect-scrollbar classes.

**Comment by marvinhuebner** [comment]
It's on the first child element from the component. Sorry, i did not see it.

But thanks for your input!

**Comment by sconix** [comment]
Its because of Angular not allowing using directives in host component which sucks a bit and makes things unnecessary complicated, but hopefully someday it will change.
