### ISSUE TITLE
camel-cased event names do not work in directive mode, dashed ones do

### ISSUE THREAD

**Issue by crystalline** [zefoy/ngx-perfect-scrollbar#132]
The documentation says this about event naming:
```
(<psEventName>)         // All Perfect Scrollbar events work as bindings.
                        // Event names are in camel case (not kebab case).
                        // Example: ps-y-reach-start -> psYReachStart
```
In practice I encountered the following bug:

Does not emit events:
```
        <div class="messages"
         [perfectScrollbar]="config"
         (psScrollY)="onScroll()"
         (psYReachStart)="onScrolledUp()"
        >
```
Does emit events: 
```
        <div class="messages"
         [perfectScrollbar]="config"
         (ps-scroll-y)="onScroll()"
         (ps-y-reach-start)="onScrolledUp()"
        >
```

**Comment by sconix** [comment]
Hard to believe since the component uses the directive with the camel case events and its working. Without them working the component would not work. Dash events do and should work with directive, but not with component.

Are you sure that you are using the 5.x version of the library?

**Comment by sconix** [comment]
I just realized that it seems that I have accidentally updated the 4.x.x readme file to have that info as well. So I guess you are using 4.x version of this library?

The documentation is wrong for the 4.x, with that you should use the dash events, I will fix the readme.

EDIT: Scratch that it seems I did update the 4.x version as well have the camel cased events, but could you tell the version anyway that you are using. Since with 4.x.x there might be a bug, I only know for sure that 5.x works.

**Comment by crystalline** [comment]
I'm using version 4.8.4 with angular version 4.3.4
Do I understand correctly that in a newer version 5.x (which requires angular 5) this behavior is corrected?

**Comment by sconix** [comment]
Ah so you are using old 4.x version, both latest versions (4.9.x and 5.x) are using the new format which was due to updating to using 1.x perfect-scrollbar.
