### ISSUE TITLE
Scrollbar flicker up and down  in ie11

### ISSUE THREAD

**Issue by hpyou** [zefoy/ngx-perfect-scrollbar#134]
![gif](https://user-images.githubusercontent.com/15992591/33747443-fbe25f18-dbfd-11e7-8b7e-e0e2c1161e81.gif)

**Comment by sconix** [comment]
At least I can not replicate such a problem on IE11. So I would need to have a Plunkr example or something to be able to check what the problem could be. Without example I can only say that I doubt thats a problem with this library.

**Comment by hpyou** [comment]
@sconix I make a plunk  http://plnkr.co/edit/CjNAF484cl1F410zZO5n?p=preview , you can see it.

**Comment by hpyou** [comment]
That demo is in native html, if in angular component, it appeared evidently.

![gif3](https://user-images.githubusercontent.com/15992591/33759867-cfc9a620-dc3e-11e7-8b4c-c4c6426863af.gif)

**Comment by sconix** [comment]
Mouse wheel does seem to act weird in that example, I don't get that sort of jumping effect though. For me its just way too fast when scrolled with mouse wheel. I would report this as a bug to the perfect-scrollbar issues. Since you are using the directive in the example the fault can not be in this wrapper library.

**Comment by hpyou** [comment]
OK,thanks anyway

**Comment by kstamatov85** [comment]
It looks the issue is the css position property of the parent wrapper. 
```
perfect-scrollbar>.ps {
    position: static;
...
```
When using <perfect-scrollbar> the position is set to static and there is no problem. When I used it as a directive my wrapper has position: relative and the flickering is on.

The bad news is, that when you use the directive if you apply position:static to your host element, the scroller is not working ok. At least I couldn't find a way even I wrap it in extra element with position: relative to handle the scroll bar.
