### ISSUE TITLE
Compatibility issue with @angular/cli 1.7.x

### ISSUE THREAD

**Issue by rodrijuarez** [zefoy/ngx-perfect-scrollbar#156]
Hello, first of all, thank you very much for creating this library! The issue that I'm having is that I tried to update the `@angular/cli 1.7.0-rc.0` because of the performance improvements made on this version, but I found the following error when upgrading:

```
ERROR in ./node_modules/resize-observer-polyfill/src/ResizeObserverSPI.js
Module parse failed: Unexpected token (13:24)
You may need an appropriate loader to handle this file type.
|      * @private {Array<ResizeObservation>}
|      */
|     activeObservations_ = [];
| 
|     /**
ERROR in ./node_modules/resize-observer-polyfill/src/ResizeObserverController.js
Module parse failed: Unexpected token (23:15)
You may need an appropriate loader to handle this file type.
|      * @private {boolean}
|      */
|     connected_ = false;
| 
|     /**
```

This is related to one of your dependencies `resize-observer-polyfill`, I'd like to know if there's any way to solve this issue, given that I'd really like to keep this library and update my angular/cli (again, for performance reasons). In the meantime I'll also try to debug this problem and see if it can be easily solved or I come up with something.

**Comment by sconix** [comment]
The angular-cli 1.7.0 pre-releases have been buggy as hell so my guess is that the bug is in the cli. So I am not going to fix the issues before they have working release out.

Once 1.7.0 is out and if there still are problems I will naturally fix them, but the quality of angular-cli releases is so bad that I don't want to look at problems caused by pre-releases.

**Comment by rodrijuarez** [comment]
@sconix makes sense, thanks for the fast response!
