### ISSUE TITLE
Refactor component to use the directive

### ISSUE THREAD

**Issue by sconix** [zefoy/ngx-perfect-scrollbar#16]

**Comment by lazarljubenovic** [comment]
What about a structural directive? Then you could use it anywhere and there would be no additional markup and (imo) weird constraint about using `div`

**Comment by sconix** [comment]
Not sure what you mean? There should not be any constraints when using the directive

**Comment by lazarljubenovic** [comment]
Yeah, my bad wording with "constraints" up there.

It's just a first-impression kind of idea (didn't check out the source in details) that instead of maintaining both

```
<div [perfect-scrollbar]="config"></div>
```

and

```
<perfect-scrollbar class="container" [config]="config">
  <div class="content">Scrollable content</div>
</perfect-scrollbar>
```

it might make more sense to API like

```
<div *perfectScrollbar="config">content</div>
```

which is anyway just sugar for

```
<ng-template [perfectScrollbar]="config">
  <div>content</div>
</ng-template>
```

Also it semantically really looks more like a structural directive since the purpose of the lib is to change the structure (the scrollbars don't just change the look and feel, they also add additional behavior).

**Comment by sconix** [comment]
Yes thats how the directive option works. This library provides both directive and component. The component provides makes the basic use case little bit easier, but the directive is which you want to use for most cases.

**Comment by sconix** [comment]
Atm component duplicates directive code and thats why this issues exists. I havent even decided if the component lives on but there is no harm to ship with both.

**Comment by sconix** [comment]
Upcoming version 4.5.0 has been refactored to avoid duplicate code, i.e. component now uses the directive.
