### ISSUE TITLE
Scroll position jumps around when using slider

### ISSUE THREAD

**Issue by gethinoakes** [zefoy/ngx-perfect-scrollbar#190]
I have the scrollbar implemented in a scrollable div that also has a https://github.com/tb/ng2-nouislider element.

The scrollbar works fine except for when the user moves the handle on the slider. The scroll position then jumps up & down. Seems to only happen on mobile devices. I've tried reacting to events to disable the scrollbar but it doesn't seem to work.

Wondering if anyone here might know why this is happening?

Thanks.

**Comment by sconix** [comment]
The reason why its happening is that the nouislider is not stopping the event propagation some of the events also go to the perfect-scrollbar. We used nouislider at some point, but can not remember how we handled this. Basically you should be able to catch the scroll/wheel/touch events from nouislider component and stop the propagation of those events.

**Comment by gethinoakes** [comment]
Thanks, I can't seem to bind to any of those events but I'll keep looking into it.

**Comment by sconix** [comment]
Sorry that I can not be more help since I don't remember how we handled it and now we are using our own slider component. At the time there was also issue in ng2-nouislider about it that it should prevent the vertical events propagation so that there is no problems using it in scrollable area, but at least back then it did not receive any attention / fixes so we ended up doing our own workaround.

**Comment by gethinoakes** [comment]
No worries, thanks for leading me in the right direction. I'll talk to the nouislider guys to see if they could put in preventing vertical events and/or take a look at their code myself.

I'll close this for you now 🙂
