### ISSUE TITLE
error TS2709: Cannot use namespace 'PerfectScrollbar' as a type.

### ISSUE THREAD

**Issue by raedwulf1** [zefoy/ngx-perfect-scrollbar#194]
This is a...
   bug report
 
What toolchain are you using for transpilation/bundling?
  @angular/cli

Environment
NodeJS Version: 8.11.2
Typescript Version: 2.7.2
Angular Version: 6.0.3
angular-redux/store version: ^9.0.0
version: 6.0.0
OS: Windows 7

Link to repo showing the issus
(optional, but helps a lot)

Expected Behaviour:
Work without any error on Angular 6, after compilation, using command "ng serve" or "ng build"
using ngx-perfect-scrollbar versions v6.0.0-0, v6.0.0 and v6.1.0

Actual Behaviour:
just after compilation finish, throw the next error:
.
.
.
chunk {main} main.js, main.js.map (main) 2.16 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 690 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 20.8 kB  [rendered]
chunk {styles} styles.js, styles.js.map (styles) 299 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 326 kB [initial] [rendered]

ERROR in node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.directive.d.ts(33,11): error TS2709: Cannot use namespace 'PerfectScrollbar'
as a type.

i ｢wdm｣: Failed to compile.

**Comment by sconix** [comment]
Perfect scrollbar should provide typings so not sure why you get that error. The example app is also angular-cli setup and it works without errors. I am not typescript expert so not sure what is causing the problem for you.

**Comment by gtoroptsev** [comment]
I had the same error, error disappeared after removing
`declare module 'perfect-scrollbar';` 
row in typings.d.ts

**Comment by sconix** [comment]
I would say there is something wrong in your setup if it can not find the typings in the perfect-scrollbar library package. If you look at the perfect-scrollbar package.json file it provides typings file so for some reason your build setup is not looking for typings in the node_modules package folders.

**Comment by Phactory** [comment]
there is "something wrong in your setup", what a great solution to this still occurring problem

thanks @gtoroptsev worked for me

**Comment by sconix** [comment]
Well the suggested workaround is a workaround. Its not a real fix, so there is still something wrong in your setup, but since this is not a Typescript forum its really hard to help with Typescript configuration issues since nobody here is a Typescript expert or at least there is a very small change to find one from this "forum" which is meant for reporting bugs.

**Comment by mikecowgill** [comment]
I'm having this issue over a year later as well. I was able to workaround it by modifying /node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.directive.d.ts

and changing 
```
ps(): PerfectScrollbar | null;
```
to 
```
ps(): PerfectScrollbarDirective | null;
```
which I believe is what it should be. Looking at the implementation for ps it returns a PerfectScrollbarDirective.

The bigger issue is that I can't build a docker image from scratch without a hacky modification of the perfect-scrollbar.directive.d.ts during the build. Would be great if this was fixed in the package.

**Comment by sconix** [comment]
The ps call does not return the directive. It returns the PerfectScrollbar instance. Its hard to fix something thats not broken :) If you are able to make reproduction I am glad to fix the issue, but so far everything points to a faulty typescript configuration not to this library.

**Comment by mikecowgill** [comment]
My apologies, ps() clearly isn't returning a PerfectScrollbarDirective.
I'll dig more into my typescript config.

**Comment by InSantoshMahto** [comment]
just reolace `declare module 'perfect-scrollbar';` into `declare module 'PerfectScrollbar';` in typings.d.ts file.
it work for me .
