### ISSUE TITLE
Forcing scroll down

### ISSUE THREAD

**Issue by beingbing** [zefoy/ngx-perfect-scrollbar#196]
I don't know if I missed something in documentation but, does you have any attribute or option to force scroll down to bottom of the list as soon as the element is shown or rendered.
I am making a chatting application and your plugin is appropriate for it but the problem is as soon as chat is rendered it is displayed from the first message, which is what I do not want, I want to show the latest message i.e., the last message hence what I want is as soon as the items are rendered the scroll automatically scrolls to bottom.
I have already seen, 
https://github.com/zefoy/ngx-perfect-scrollbar/issues/21
and 
https://stackblitz.com/github/zefoy/ngx-perfect-scrollbar/tree/master/example

They were informative and tried them also in my code, but they didn't worked.

Some information about my application -
I am trying to build a chat application on angular 5.

**Comment by sconix** [comment]
Readme has the API described and there are functions to scroll to the bottom. There is no build in or native bottom scrolling in browsers so the only way to do it is to build the scroll control yourself with the scroll API's.

**Comment by lorado** [comment]
As sconix said, you can use API to achieve this behaviour.

In my application there is also a chat part. Here is my solution:

1. Create a reference to the perfect-scrollbar in your component:

```html
<perfect-scrollbar [config]="{...}" #chatPS>...</perfect-scrollbar>
```
```ts
@ViewChild('chatPS') chatPS: PerfectScrollbarComponent;
```
You may also use PerfectScrollbarComponent in ViewChild, but I have multiple scrollbars, that's why I get it by reference name

2. After you initiated all your messages, just call `this.chatPS.directiveRef.scrollToBottom()`, and voila, you are at the bottom. Be sure, that `this.chatPS` is available. If you e.g. hide your scrollbar with `*ngIf`, then before accessing `this.chatPS` call `this.changeDetectorRef.detectChanges()`

3. React to incoming messages, and scroll to bottom. For this case I scroll to bottom with animation: `this.chatPS.directiveRef.scrollToBottom(0, 300)`

I hope you can solve your problem

**Comment by beingbing** [comment]
thanks @lorado, your example did the trick.

**Comment by Art2058** [comment]
thanks @lorado 
good `this.changeDetectorRef.detectChanges()`!!
