### ISSUE TITLE
ngxPerfect-Scrollbar not working inside material tab

### ISSUE THREAD

**Issue by karthickDhanapal** [zefoy/ngx-perfect-scrollbar#201]
Hi 

I am using ngxPerfect scroll bar inside material tab but the rail-x and rail-y has the same top and left value there is no bottom and right added to it

![image](https://user-images.githubusercontent.com/33171571/43639750-e4d738a4-973a-11e8-9037-0a5bd8afb665.png)

**Comment by sconix** [comment]
Hard to say from that what could be the problem. If you can make a simple stackblitz demo of the issue then I could have a closer look. Its possible that in some situation you need to call the update function through the directive reference for the perfect-scrollbar to update the scrollbars. The directive does its best to notice the need for it automatically, but there might be cases where it fails to do so although have not seen any myself.

**Comment by karthickDhanapal** [comment]
thanks for the fast reply @sconix  Ill be sharing the demo as soon as possible..

**Comment by karthickDhanapal** [comment]
Hi @sconix 

Actually I am facing some difficulties to upload the sample project in stackblitz. I have didn't done any ts changes we have made only html changes so can you please check this html code as sample 

**HTML:**

 <mat-tab-group>
    <mat-tab label="Tab 1">
  <div>
      <div class="scroll-container ps hi" fxFlex="auto" #perfectscroll="ngxPerfectScrollbar" [perfectScrollbar]="config" >
        <div class="scrollable-content">
          <iframe src="https://developer.github.com/v3/issues/" width="900px" height="850px" scrolling="no">
         
        </iframe>
        </div>
      </div>
    </div>
    </mat-tab>
    <mat-tab label="Tab 2">Content 2</mat-tab>
  </mat-tab-group>
  
**Can you please provide your valuable inputs on this HTML code**

**Comment by karthickDhanapal** [comment]
Hi @sconix ,

Please find the sample code with issue in stackblitz :

APP URL: https://mat-stretch-tabs-so-b7tn17.stackblitz.io/

EDITOR_URL:https://stackblitz.com/edit/mat-stretch-tabs-so-b7tn17

@sconix  We stuck with this badly please help me out here.....

**Comment by sconix** [comment]
Have you tried the component instead of directive? The perfect-scrollbar has couple style issues in some situation that I have fixed in the component styles. So first you could try if the component works better. I will have a better look at the example as soon as I have time, but in the meantime you could try the component since with quick look at the problem it looked bit like the styling issue.

**Comment by karthickDhanapal** [comment]
Hi @sconix ,

I have tried the component level but i am not able to catch it up.Same scenario is produced/ Can you please help me out in the sample code that have been populated in stackBlitz site.

**Comment by sconix** [comment]
I just quickly tried component and it worked as it should when adding the styles for the other elements so that they have some height set. One thing to remember with scroll areas is that they always need height. Either via flexbox or height styles, otherwise it just takes the height of the content.

So just switch to the component (or fix the scrollbar locations with styles when using directive) and make sure that every container in your app has height set. If you have look at your current example already the html and body elements heights are more than the height of the page so there is no change that any scrollarea would work.

**Comment by karthickDhanapal** [comment]
ok thanks @sconix  I'll try and update you. As of now ill close this request.
