### ISSUE TITLE
How to make scrollbar start from bottom?

### ISSUE THREAD

**Issue by Trfnthbyf** [zefoy/ngx-perfect-scrollbar#21]
Hi, can you help me? Is it possible to make the scroll bar starts at the bottom? I'm trying to create a chat application, and I want that all the new messages are added at the bottom, so I need to make scroll bar start at the bottom.  How do I make it?

Thank You in Advance.

**Comment by sconix** [comment]
It seems that perfect scrollbar does not offer any ready options for that kind of use so you need to do it the traditional javascript way i.e. set scrollTop to scrollHeight always when you want to take the scroll to the bottom.

I can add scrollToTop and scrollToBottom functions for the component to make it bit easier so that you can just call scrollToBottom when ever you have new messages and want the scroll to go to bottom.

**Comment by Trfnthbyf** [comment]
It would be great. I'm trying to  set scrollTop to scrollHeight this way: this.myScrollContainer.nativeElement.scrollTop = this.myScrollContainer.nativeElement.scrollHeight;
and nothing happening. Maybe I do something wrong.

**Comment by sconix** [comment]
I am releasing 2.0.3 in hour or so, it has the scrollToBottom helper function so you can just use viewchild to get the ref to the scrollarea and can then call scrollToBottom.

**Comment by Trfnthbyf** [comment]
cool, thanks
