### ISSUE TITLE
error on importing ngx-perfect--scrollbar

### ISSUE THREAD

**Issue by roxangui** [zefoy/ngx-perfect-scrollbar#216]
<img width="534" alt="screen shot 2018-10-17 at 5 23 17 am" src="https://user-images.githubusercontent.com/7142764/47056411-4ae7b480-d1cd-11e8-91b0-3ba9b6307f19.png">

error on importing it to module

`import { PerfectScrollbarModule, PERFECT_SCROLLBAR_CONFIG, PerfectScrollbarConfigInterface } from 'ngx-perfect-scrollbar';
const DEFAULT_PERFECT_SCROLLBAR_CONFIG: PerfectScrollbarConfigInterface = {
  wheelPropagation: true,
  suppressScrollX: true
};`

`@NgModule({
  declarations: [
    ....
  ],
  imports: [
    ....
    PerfectScrollbarModule,
    ....
  ],
  providers: [
    { provide: PERFECT_SCROLLBAR_CONFIG, useValue: DEFAULT_PERFECT_SCROLLBAR_CONFIG }
  ],
  bootstrap: [AppComponent]
})`

<img width="384" alt="screen shot 2018-10-17 at 5 23 08 am" src="https://user-images.githubusercontent.com/7142764/47056333-e2003c80-d1cc-11e8-8444-41aa291fe254.png">

**Comment by roxangui** [comment]
<img width="1007" alt="screen shot 2018-10-23 at 3 59 08 pm" src="https://user-images.githubusercontent.com/7142764/47359048-b43f5a00-d6dc-11e8-9f9f-9603299ae8ec.png">

i found this error tag on node_modules after executing install steps on ngx-perfect-scrollbar and include in the module. i'm not sure whats the issue but its a clean install with the package dependency about mention.

**Comment by sconix** [comment]
For installed npm package that config should not be used by anything. I could just leave out it from the distributed package. but there should not be no harm to keep it in the package afaik. So that error should be irrelevant since the package is already compiled it does not have any typescript code.

**Comment by sconix** [comment]
Really hard to say what could be your problem since in our Angular cli projects and in the example apps there is no such import errors. The weirdest thing is that the error looks like its coming from Webpack and the webpack in Angular cli should be blackboxed so there should not be any differences between build setups.

**Comment by roxangui** [comment]
i've tried downgrading and upgrading webpack it all goes back to the issue.

<img width="544" alt="screen shot 2018-10-24 at 9 57 03 am" src="https://user-images.githubusercontent.com/7142764/47409247-3a0de480-d773-11e8-8c37-2c51d69b8499.png">

here is my package

<img width="439" alt="screen shot 2018-10-24 at 9 57 13 am" src="https://user-images.githubusercontent.com/7142764/47409256-42feb600-d773-11e8-98bc-d79971412450.png">

**Comment by sconix** [comment]
Well webpack version should come from installing angular cli so there really should not be possibility of version mismatch etc. We have the almost the same versions (only rxjs is 6.2.x) in our Angular CLI project atm and we do not get that error. I would try once more wiping node modules, wiping npm cache and doing fresh install after that. That's all I can think of.
