### ISSUE TITLE
Anchors not supported

### ISSUE THREAD

**Issue by MVTec** [zefoy/ngx-perfect-scrollbar#231]
Hi ,
 In my Application I have a "Help" page with Index of Contents and Content. 
Anchors are also there for within Page easy navigation.
Now after using ngx-scrollbar the anchors don't work anymore.

Please find attached code snippet from HTML template.
[help.txt](https://github.com/zefoy/ngx-perfect-scrollbar/files/2778618/help.txt)

Thanks

**Comment by sconix** [comment]
There is no way that how perfect-scrollbar could support Angular routers scrolling. You would need to implement it yourself via directive etc. Since the router has no means of knowing which is the actual scroll element since PS wraps it withing couple elements due to implementation specific requirements.

**Comment by MVTec** [comment]
Ok ,Thanks Sconix
