### ISSUE TITLE
Scroll to the bottom, continue to scroll the scroll wheel, the page content continues to scroll

### ISSUE THREAD

**Issue by EightCanisters** [zefoy/ngx-perfect-scrollbar#242]
When I scroll down to the bottom using the mouse wheel, the middle contents continue to scroll up and the **psYReachEnd** event is not triggered.
Here's my code:
```
xxx.component.html:
<div [style.height.px]="200" class="transcript ps" [perfectScrollbar]="config" (psXReachEnd)="onScrollEvent($event)" (psYReachEnd)="onScrollEvent($event)" (psXReachStart)="onScrollEvent($event)" (psYReachStart)="onScrollEvent($event)">
  <div style="height:500px;">
    <div   *ngFor="let datum of data" > {{datum}}</div>
  </div>
</div>

xxx.component.ts:
import { Component, EventEmitter, ElementRef, AfterViewInit, Input, Output, ViewChild } from '@angular/core';
import { PerfectScrollbarConfigInterface, PerfectScrollbarDirective } from 'ngx-perfect-scrollbar';

@Component({
  selector: 'xxx-pane',
  templateUrl: './xxx.component.html',
  styleUrls: ['./xxx.component.scss']
})
export class XxxComponent{
  data: object[];
  config: PerfectScrollbarConfigInterface = { };

  @ViewChild(PerfectScrollbarDirective) directiveRef?: PerfectScrollbarDirective;

  constructor() { }
  onScrollEvent(event: any): void {
    console.log(event);
  }
}
```

I have been looking for a long time without finding the answer. What went wrong?

**Comment by sconix** [comment]
That is called scroll propagation. There are configuration setting for wheel propagation. If you need to control both wheel and touch propagation then your only option is to use autoPropagation feature of the component which does stop the propagation on end, but allows it after a small pause in scrolling.

**Comment by EightCanisters** [comment]
I think you may not understand what I'm saying here: scroll down to the bottom of the box, keep scrolling, and the box keeps getting taller and the content keeps scrolling up.
I use them by directive, referring to examples in examples.The config parameter is the same as the example, the only difference being that I defined a set of styles myself, and then I had this problem.

Finally, I found the code that caused the problem:
.ps--active-x > .ps__rail-x,
.ps--active-y > .ps__rail-y {
  display: block;
  border: 1px solid gray;
}
But I don't understand why.........

**Comment by sconix** [comment]
Ok then I miss understood, but what you describe does not make that much sense indeed :) And I have bit trouble believing it would be those styles that cause it. It sound more like a problem in your page styles.

One thing could be that if you have some global styles that override normal box-sizing styles so that the border style starts to cause issues for the PS calculation. So maybe check if you have some generic box-sizing styles "leaking" to the ps elements.

**Comment by Alexandru-Pirvu** [comment]
I also have this issue and it was indeed due to my code, meaning that I had a border on the perfect scroll element.
It does not seem the correct behavior.

The workaround I used was to create a container on top of the scrolling element and put the border on the container.

**Comment by pankaj-yadav0507** [comment]
I faced the same issue, for me the problem was even max-height value.

**Comment by pankaj-yadav0507** [comment]
I faced the same issue, for me the problem was even max-height value.
`    <div class="ps" style="position: relative; max-height: 80vh;" [perfectScrollbar]="{}">
`
I changed it from 80vh to 81vh and it worked perfectly.

**Comment by pankaj-yadav0507** [comment]
I also faced the same issue, for me the problem was even max-height value.
<div class="ps" style="position: relative; max-height: 80vh;" [perfectScrollbar]="{}">
I changed it from 80vh to 81vh and it worked perfectly.

After digging more I found out that the real issue was incorrect rounding of max-height because of 80vh. Changing it into px everything worked fine on all the devices.

**Comment by pankaj-yadav0507** [comment]
I also faced the same issue, for me the problem was even max-height value.
`<div class="ps" style="position: relative; max-height: 80vh;" [perfectScrollbar]="{}">
`I changed it from 80vh to 81vh and it worked perfectly.

**After digging more I found out that the real issue was incorrect rounding of max-height because of 80vh. After changing it into px everything worked fine on all the devices.**
