### ISSUE TITLE
How to use perfect scrollbar methods

### ISSUE THREAD

**Issue by mhelaiwa** [zefoy/ngx-perfect-scrollbar#25]
Hi,
I want to call `Ps.update(container);` when active route changes. But how to call these impeded methods from my component ? Is there any service I could inject to my component and call these methods ?
thanks

**Comment by mhelaiwa** [comment]
I think it will be helpful to subscribe to router events and call update `Ps.update(container);` on `NavigationEnd` event. You could also make a config option to enable this auto update feature.

**Comment by sconix** [comment]
You need to get the reference to PerfectScrollbarComponent / Directive with ViewChild/ContentChild i.e. the normal Angular 2 way. Then you can call the provided functions or even get the reference to the perfect scrollbar library and do anything that the library supports.

The component does auto update in all normal situations i.e. when the size of the scroll area or content changes. Directive is bit less automatic since its meant for custom use cases and for building your own component which takes care of the auto updating etc. The component does not do auto update on router navigation end since there should not be need for an update the size changes detection should be enough for most common cases.
