### ISSUE TITLE
Smooth scrollTo option

### ISSUE THREAD

**Issue by Bbbrinks** [zefoy/ngx-perfect-scrollbar#28]
I'm using the scrollTo method in my project but the scrolling is a bit to 'instantaneous' for my usecase.

Would I be possible to add a scrollSpeed to the scrollTo method? Or should I implement that outside the perfect-scrollbar.

**Comment by sconix** [comment]
Its possible, but atm I don't have time for such feature. PR is always welcomed if somebody wants to add such option. Anyway nothing prevents you making the smooth scroll outside of this library since you can either use the scrollTo within some smoothing timer or get the native element reference and do the smooth scrolling by some other library / implementation.

**Comment by Bbbrinks** [comment]
Ok thanks for the quick response. I will look into making a Pull request if my employer agrees that it's worth my time:)

**Comment by sconix** [comment]
There will be speed option in the upcoming 4.5.0 release.
