### ISSUE TITLE
Unable to use PerfectScrollbarModule.forRoot() under the submodules with Lazy-loading.

### ISSUE THREAD

**Issue by gsotiv** [zefoy/ngx-perfect-scrollbar#41]
While I imported under the SharedModule, it said following issues.

```
ERROR Error: Uncaught (in promise): Error: 
      Application called PerfectScrollbarModule.forRoot() twice.
      For submodules use PerfectScrollbarModule.forChild() instead.
```
 Any solution to avoid this?
Regards

**Comment by sconix** [comment]
You can't and should not use forRoot in submodule its as the name says for root module. So like the error says use forChild or just leave out the for* part all together. The method is there to provide global configuration, so you don't need to use it since you can provide the configuration manually as well or just not do it at all.
