### ISSUE TITLE
How can I getthe scrollbar's scrollTop at every moment?

### ISSUE THREAD

**Issue by xuwenqing2014** [zefoy/ngx-perfect-scrollbar#52]

**Comment by sconix** [comment]
If you mean while scrolling then perfect scrollbar has scroll event.

**Comment by xuwenqing2014** [comment]
sorry, I mean that how to get the coordinate of scrollbar, x or y?

**Comment by sconix** [comment]
Just like with any other / normal scroll area, just get the scrollTop etc. values from the native element. I could add a helper function for next release.

**Comment by xuwenqing2014** [comment]
yes, but I think deeply， it also can't solve my project's problem. the problem is: After the content add more data dynamically, the scrollbar will move to the top, what I want that  don't move the scrollbar's position. Could you help me ? I have commit the demo to my github repository, it can show the problem. please.

**Comment by sconix** [comment]
Can't say what your problem is since we do add content dynamically in our project and adding content should never reset the scroll position. It seems that you are adding content into the beginning of the scroll so naturally the scroll position won't stay in the same position. So if you want to add stuff into beginning you need to get the scroll position from bottom (scrollHeight - scrollTop) before adding the content and then adjust the scroll position after content is added to the previous position with scrollToBottom function.

The next 4.5.0 version will have geometry helper function to get the scroll position / size without the need to get the size through elementRef.

**Comment by xuwenqing2014** [comment]
Thanks, I understand，so When will the next 4.5.0 version come out?

**Comment by sconix** [comment]
Soon, during this week.
