### ISSUE TITLE
The scrollbar does't work when I update to the  vision 4.5.0

### ISSUE THREAD

**Issue by xuwenqing2014** [zefoy/ngx-perfect-scrollbar#60]
When I update to the vision 4.5.0, everything does't work, it can't scroll and the scrollbar is dissappear, Is there anything I need to pay attention to?

**Comment by sconix** [comment]
The component has been refactored to use the directive. So if you have custom styles for the component those need to be updated since now the perfect scrollbar element is the first child element and not the host element.

Other than that there might be still some situations where the components styles wont work automatically and for those I would need Plunker example or at least bit more info if there is anything special in the way you use the component. I have already found one small style bug and 4.5.1 will be out soon so its possible that it already fixes your problem.

**Comment by sconix** [comment]
Actually I am pretty sure that the 4.5.1 will fix your problem, but if you want you can try adding global style below to test if that fixes your problem. Without those the actual scrollarea wont get proper size in every situation.

perfect-scrollbar { .ps { width: 100%; height: 100%; }}

**Comment by sconix** [comment]
Or maybe I just release 4.5.1 already so you can test, let me know if it does not fix the problem.

**Comment by xuwenqing2014** [comment]
It's very strange， one scrollbar can work normally, one scrollbar does't work, and others can work with scrollbar disappear.

**Comment by sconix** [comment]
You mean that 4.5.1 did not fix the problem? Area you using flex styles / layout library or do you define the perfect-scrollbar component height via styles?

There is still problem when using flex-layout library which I am currently fixing, but it should now work if you define the size with width/height.

**Comment by xuwenqing2014** [comment]
I have't use flex styles, I am using my own css to redifine the styles, all perfect-scrollbar component have defined width and height. but, just one perfect-scrollbar component can work normally, others does't work. all perfect-scrollbar component can work normally in version 4.4.0.

**Comment by sconix** [comment]
So did you try the 4.5.1 already? I released it about 30 minutes ago.

**Comment by xuwenqing2014** [comment]
I have install the 4.5.1 twice to try twice, not 4.5.0

**Comment by sconix** [comment]
Ok, I will try to see if I can get the problem reproduced. I have tried to test without using flex layout, but I guess I am missing something since it works for me. 

Have you checked using inspector that is it the ps element that is not correctly sized or if there is some other problem? If you use the inspector the first child of the perfect-scrollbar component should have width/height 100% and it should be the same size as the component which size you are defining if I understood correctly.

**Comment by xuwenqing2014** [comment]
I know the problom, 'perfect-scrollbar' should be 'display: block', everything is ok

**Comment by sconix** [comment]
Ah that one again :) Just out of curiosity what OS / browser you are using? Since I can't reproduce that requirement in any of my browser / platform tests. 

I will add that for 4.5.2 which I release real soon. It should now have fully working component for all supported browsers.

**Comment by xuwenqing2014** [comment]
I am using windows and chrome

**Comment by sconix** [comment]
Ah that explains it, I will include it in my tests. I have though that Chrome would be the same on all platforms so I only test it in my Linux setup. Please let me know if 4.5.2 still gives you problems, I release it within the next hour, still doing some check on iOS platform.

**Comment by sconix** [comment]
I just released 4.5.2.

**Comment by xuwenqing2014** [comment]
The problem is solved, thanks
