### ISSUE TITLE
No touchmove event on the scrollbar

### ISSUE THREAD

**Issue by Nehluxhes** [zefoy/ngx-perfect-scrollbar#64]
Hi,

Dragging the scrolled element or just tapping the scrollbar works fine, but not dragging the scrollbar itself on mobile (works on browser).

**Comment by sconix** [comment]
Yes thats how the perfect-scrollbar library is made, i.e. the scrollbar is just an indicator on mobile and not draggable. It mimics the normal mobile scrollbars which are just indicators not actual scrollbars. I haven't looked more closely to the perfect-scrollbar library that can this behavior be changed with some configuration or not since this is how we want it to work in our app.
