### ISSUE TITLE
The scrollbar can't scroll when I am selecting the content and the cursor is outside scroll area

### ISSUE THREAD

**Issue by xuwenqing2014** [zefoy/ngx-perfect-scrollbar#65]
When I selecting the content and the cursor is outside scroll area, the scrollbar can't scrollTo the direction that I moved to.

**Comment by sconix** [comment]
The selection scroll is disabled as a default in the perfect-scrollbar since it can cause problems. See the perfect-scrollbar documentation about enabling it:

handlers

It is a list of handlers to use to scroll the element.
Default: ['click-rail', 'drag-scrollbar', 'keyboard', 'wheel', 'touch']
Disabled by default: 'selection'

**Comment by pradeepmu-kore** [comment]
I have problem with on text selecting in pdf doc not able scroll down like native scroller. its moving out of the container & text is not selecting within the container, not able drag scroller down like native. Can you provide input, how to fix in ngx-perfect-scrollbar lib

Im using:
angular 7
ngx-perfect-scrollbar: ^8.0.0
