### ISSUE TITLE
Any way to have the scrollbar visible before scrolling?

### ISSUE THREAD

**Issue by JanSchuermannn** [zefoy/ngx-perfect-scrollbar#72]
The module works perfectly, but right now the scrollbar (rail and bar) only shows up when i start scrolling. 

Is there a way to have at least the rail always visible?
It's kinda difficult to see whether a container is scrollable for the user if the scrollbar doesn't show up immediately...

Thanks for any help!

**Comment by sconix** [comment]
It shows up on hover. If you want it to show all the time you can always override the styles.

**Comment by JanSchuermannn** [comment]
It doesn't show onHover for me, only when I scroll.
The rail doesn't have a height set on the element until I scroll, I assume this is somehow wired to the events firing on the scrollbar (but haven't figured out yet how exactly)

**Comment by sconix** [comment]
If the rail does not have height then the perfect scrollbar update function has not been called after the view has been rendered. The library calls the update automatically on changes that it can detect, but its always possible that your applications hides/shows the scroll area so that the library won't detect the change, then you need to manually call the update function. The library does it automatically on render and if using hidden attribute to toggle the showing. 

You can call the update function through the component/directive reference.

**Comment by JanSchuermannn** [comment]
Working perfectly now with manually calling the update method, thanks!

In case someone else experiences a similar issue, here's what's causing the automatic update to fail:

I have a form that contains (besides several other controls) two FormArrays, initially containing each one control.
I am then dynamically adding/removing controls from the array via button click. The changes to the DOM (*ngFor) are not being detected by the scrollbar directive, assumingly *ngFor doesn't fire the proper events for that.
Anyway, calling the update method after adding/removing a control shows the scrollbar immediately.

Thanks @sconix for the help!

**Comment by sconix** [comment]
Thanks for the info, I will try to replicate this at some point to see if I can improve the library to handle this automatically. Since it should do it automatically with ngFor since its normal element creation, but perhaps  you have some layout / styling that causes the height to be 0 on initial render. Anyway I will verify the use case which you described at some point to see if its something that I can improve on.

**Comment by JanSchuermannn** [comment]
In case it helps:

just calling the update method doesn't work, I had to wrap it in a timeout after adding or removing elements. maybe if you do that directly in the library it would work instantly

**Comment by sconix** [comment]
Thanks, I already though that its done in timeout, but seems thats only in my swiper wrapper lib. Will add that fix for this one as well.

**Comment by sconix** [comment]
Latest release has the update wrapped into timeout so that the update call works in more cases.
