### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by volser** [zefoy/ngx-perfect-scrollbar#75]
I used chrome profiler tool to get logs
https://ibb.co/mrKN1k

and perfect-scrollbar.directive.js forced reflow is a likely performance bottleneck

do you have any ideas what could be?
Is it necessary to calc width/height on ngDoCheck?

thanks!

**Comment by sconix** [comment]
Its necessary for not having to call update manually all the time. Checking offsetHeight/Width does force reflow but normally it should not be that heavy operation if there are no changes in the DOM.  I have planned to optimize this though, but haven't given it yet big priority because imho its performance issue if not using onPush and when not using it you wont get that great performance anyway. 

What I am considering is to use element-resize-detector library which provides scroll strategy for noticing element resizes. The only down side is having the extra library dependency, but I think using the library should be much more lightweight than using the ngDoCheck + offset checking. I just would need to find time to actually make sure that there is a performance gain from bringing in this library.

I can put out an experimental release of the library with the change if you really think the ngDoCheck is causing performance issues in your app and you are willing to check / test if the other method is actually better.

**Comment by volser** [comment]
I'm ready for testing

**Comment by sconix** [comment]
I released 4.6.0-1 beta version.

**Comment by volser** [comment]
Thanks!
as for me - better, no force reflow ), will test more closely

**Comment by sconix** [comment]
There hasn't been any problems in our app neither so I think I will just release this tomorrow since I think this is better.

**Comment by srcn** [comment]
@sconix The element-resize-detector library puts an extra div inside every container that have perfectScrollbar directive or the component. I know that's how it detects the resize but this is a huge problem since it breaks some flex layouts such as space-between.

Flex doesn't care about if the div is visible or not so it puts space in between the element-resize-detector div and other elements and causes layout problems.

Preview:
![screen-shot-2017-09-18-at-12 53 41](https://user-images.githubusercontent.com/117369/30537220-7e57d684-9c71-11e7-8bd2-f80be34c3a15.png)

Source:
![screen shot 2017-09-18 at 13 02 30](https://user-images.githubusercontent.com/117369/30537269-ab479e4a-9c71-11e7-8fb2-e19df6d63e94.png)

**Comment by sconix** [comment]
You can very easily fix that problem. Just use one extra div which wraps the scrollable content and set the flex attributes for that div and not for the perfect-scrollbar component. This is anyway better since that way the perfect-scrollbar library can not effect your flex styling.

**Comment by srcn** [comment]
So you suggest me to go through thousands of lines of code and re-structure everything?

Anyways, thank you for giving me enough push to create my own wrapper directive. Good luck to you and thanks for the library.

**Comment by sconix** [comment]
Well that was just a suggestion... Its just something that is needed anyway as I said. Without the wrapping div any release to perfect-scrollbar can break flex-layout library. We have that problem with Swiper library which also requires a wrapper div or Swiper cleanup process breaks flex-layout library usage and the same could basically happen with any release to perfect-scrollbar.

The reason why I can not put the wrapper div into the component is that then you would not be able to easily adjust the flex attributes of it. You would need to do it with styles which would rule out the flex-layout library usage.

So not sure why you need your own library. The directive is designed so that you can easily make your own custom perfect-scrollbar component where you can have the wrapper div etc. And what comes to the thousands of lines of code, replacing the perfect-scrollbar component with your own custom one that uses the directive is one line command line operation or one replace command from IDE.

And I am always open for suggestions. Atm I am not just aware of anything that I could do within the library. As said I can not place the wrapper into the component since then you would not be able to use it with flex-layout library. And going back to the old change detection is not an option neither since its way too heavy. The way you have been using this library its been just luck that it works without the wrapper element when using flex-layout library.

**Comment by sconix** [comment]
Just to update on this, the next release will not include the element-resize-detector anymore. It was causing problems on certain type of contents due to the added element. I am now trying to use resize-observer-polyfill which wont add any elements. So far its looking promising.
