### ISSUE TITLE
Scrollbar doesn't work outside of display: flex elements.

### ISSUE THREAD

**Issue by Bbbrinks** [zefoy/ngx-perfect-scrollbar#77]
When you remove the display: flex in the following example the Y scrollbar isn't showing up.

Tested in chrome with version 4.5.6
 ```
 <div style="
position: absolute;
top: 100px;
bottom:100px;
left: 150px;
background-color: #cecece;
 display:flex;
">
    <perfect-scrollbar>
     .. long content
    </perfect-scrollbar>
  </div>
```

**Comment by sconix** [comment]
Scollareas always needs height it wont work otherwise. So if you are not using flex to set the height for the perfect scrollbar then you need to set it using height parameter. But scroll areas always need a specific height. So add height: 100% to the perfect-scrollbar component styles.

I will look into adding default style of height 100%, but I haven't done it yet since it can cause problems since its not always what is wanted. Even the perfect-scrollbar library is not using any height as default, you need to always specify it with styles.

**Comment by Bbbrinks** [comment]
Ah yes adding 100% to the <perfect-scrollbar> element works. Might be nice to have this in the documentation/example for people that are not using flexbox.

**Comment by sconix** [comment]
I think I will add that style for next release. At least I could not find any problems having it with flexbox either so should be safe to add that.
