### ISSUE TITLE
Need info about the compatible version of the library and the change log

### ISSUE THREAD

**Issue by MurhafSousli** [zefoy/ngx-perfect-scrollbar#95]
Hi @zefoy,

I just updated this module to **v4.8.4** and the original library to **v1.0.3**, the current doc does not tell which version of the library is compatible, and I think there is a breaking changes. 

The `scss` files we used before has been thrown out from the package (we cannot override styles anymore), the bars disappeared and there is a huge height added at the end of the scrolling element, probably a miscalculation from the library! 

I don't know what changed or which version of the library is compatible with this wrapper, can you perhaps update the docs and add **CHANGELOG.MD** to let users know what has been changed.

Thanks!

**Comment by sconix** [comment]
The package.json has the correct version which should always get installed. Of course package.json wont prevent someone manually installing incompatible version, but I don't see it very beneficial to document the version since they can be seen in the package.json.

So to answer the question 0.8.x is the current version that is supported. I already have 5.0.0-8 ready for release with support for 1.0.x, but I am waiting for beta.10 release of flex-layout so that the example app works with Angular 5. So for now just use 0.8.x and I am hoping that within a week I can make the new release. The upcoming 5.x release of this library will work with Angular 4/5 and use the latest perfect-scrollbar.

**Comment by sconix** [comment]
About the changelog you can see the releases section, there is detailed info about the changes for every release. Depending on the version you upgraded, there has not been any big changes for a while, the only bigger change was when I updated the component to use the directive which might cause the need to update custom styles although not necessery (can't remember the version when I did that change, but its been a while).

**Comment by MurhafSousli** [comment]
@sconix Thank you
