### ISSUE TITLE
How to use ngx-perfect-scrollbar directive with default theme

### ISSUE THREAD

**Issue by sosharma1403** [zefoy/ngx-perfect-scrollbar#97]

**Comment by sconix** [comment]
Like the readme says. If you use directive only then you need to load the theme yourself. Be sure to check the correct branch for the readme (4.x.x branch) the master has already info about the next release which is out soon and uses 1.x version of perfect-scrollbar.

**Comment by wendellmva** [comment]
Uhm, it could be me, I am not quite sure but I think you are cursed with knowledge because this;

> [usePSClass]            // Use ps class (needed by the ps theme styles).

might make perfect sense to you but to me it's perfectly nonsense. I see a ps-default-theme in theme.scss but how to glue it onto the component lays beyond my grasp.
Could you kindly point to an example where the default style is overridden in such a fashion?
Thank you, your component is greatly appreciated.

**Comment by sconix** [comment]
So what are you asking, the title of this issue is how to use default theme, but in the above you are asking about overriding default styles. So which is it that you want to know, they are totally different things :) Its more clear to make your own issue when things are not connected.

To load the default theme you just import the theme file like the readme says. To override style you just provide your own styles normally. There is no special tricks needed. The input attribute you mentioned does just disable the perfect-scrollbar class when none of the component styles has an effect and you can provide your own custom styles.

**Comment by sosharma1403** [comment]
@sconix Css part of it is not working for me.. 
Can you please provide a link to plunker showing prefect-scrollbar as a directive with default theme?

**Comment by sconix** [comment]
Sorry, but at the moment I am busy with getting new releases out with Angular 5 etc. The component only differs from directive so that it imports the css file so as long as you import it like the readme says it should work. Just make sure that you import it in global style file and not in component styles or if you do it in your component style file then you need to turn off the Angular style encapsulation. Importing css style file and checking why its not working is basic web development and not specific to this library. If you are not familiar with Angular style system then you might want to just import the perfect-scrollbar style file from the cdn in your index.html file like:

```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery.perfect-scrollbar/0.8.1/css/perfect-scrollbar.min.css" />
```

If you still can't get it to work you can make an example in Plunker and I can have a quick look from there.
